### ISSUE TITLE
Add Bilboard mode to the Sun corona

### ISSUE THREAD

**Issue by ultrazar** [Hoimar/Planet-Generator#17]
Add this in the Corona shader of the Sun. In the Vertex method. I tried it and works

![image](https://user-images.githubusercontent.com/48863881/121717955-0ded3080-cae2-11eb-8946-6a5ae8d222a7.png)

From: https://github.com/godotengine/godot/issues/16561

**Comment by Hoimar** [comment]
Would you be willing to create a pull request? Of course I can also do the changes by hand soon-ish.
