### ISSUE TITLE
Doesn't work on HTML5

### ISSUE THREAD

**Issue by ultrazar** [Hoimar/Planet-Generator#18]
It simply doesn't patch the terrain, goes completely black.

Specs:
- GPU: GTX 750 (GLES 3.0)
- Browser: Opera, Chrome

And throws this error every time that tries to generate the terrain:
 - GL_INVALID_OPERATION: It is undefined behaviour to have a used but unbound uniform buffer.

**Comment by ultrazar** [comment]
Update: Threads are not currently available in godot for HTML5. Simply the TerrainJobs doesn't run.

**Comment by Hoimar** [comment]
Hey, thanks for the report. You could try to export in "Thread" mode (in export settings under "Variant"). Your browser needs to have `SharedArrayBuffer` enabled (see [here](https://teddit.ggc-project.de/r/godot/comments/mvwim9/godot_33_html5_threads_export_type_wont_run_on/) for example).

You could try to turn of mutlithreading in `const.gd`, though it will tank performance obviously.

**Comment by ultrazar** [comment]
> Hey, thanks for the report. You could try to export in "Thread" mode (in export settings under "Variant"). Your browser needs to have `SharedArrayBuffer` enabled (see [here](https://teddit.ggc-project.de/r/godot/comments/mvwim9/godot_33_html5_threads_export_type_wont_run_on/) for example).
> 
> You could try to turn of mutlithreading in `const.gd`, though it will tank performance obviously.

Now it works perfect! Thanks! 
BTW I can't see any constant for turning off the multithreading

**Comment by Hoimar** [comment]
That's great to hear, I didn't even expect it to work flawlessly!

Oh, you're probably working on the `master` branch, sorry. You will have to check out the `dev` branch to find the constant `THREADS_ENABLED` in  [`constants.gd:5`](https://github.com/Hoimar/Planet-Generator/blob/dev/addons/hoimar.planetgen/scripts/constants.gd#L5).
